services:
  theatre:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - my_media:/files/media
    command: >
      sh -c "./start.sh"
    depends_on:
      - db


  db:
    image: postgres:16.0-alpine3.17
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - my_db:$PGDATA

volumes:
  my_db:
  my_media:
