# Generated by Django 5.1.4 on 2024-12-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_alter_genre_name_alter_ticket_performance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="theatre.actor"
            ),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="movies", to="theatre.genre"
            ),
        ),
    ]
